CREATE TABLE IF NOT EXISTS users
(id SERIAL PRIMARY KEY NOT NULL,
username VARCHAR(60) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
date VARCHAR(10) NOT NULL,
hash VARCHAR(255) NOT NULL,
description VARCHAR(500),
flag VARCHAR(30),
bg_flag VARCHAR(30),
discord_id VARCHAR(100),
coalition_id INTEGER,
is_verified BOOLEAN DEFAULT FALSE,
auth_type VARCHAR(50));
